###############################
#   STM32L0 Discovery Board   #
###############################

PROJECT         := Discovery
DEVICES         := STM32L053
BUILD_TYPE      := Debug
WORKSPACE_ROOT  := ../..
MBED_LIBS       := rtos
#VERBOSE         := 1

include $(WORKSPACE_ROOT)/build/mbed.mk
