###############################
#   STM32L0 Discovery Board   #
###############################

PROJECT         := Discovery
DEVICES         := STM32L053
#BUILD_TYPE      := Debug
WORKSPACE_ROOT  := ../..
NO_FLOAT_SCANF  := 1
NO_FLOAT_PRINTF := 1
#MBED_LIBS       := rtos
#VERBOSE         := 1

include $(WORKSPACE_ROOT)/build/mbed.mk
